language: python
python:
  - "2.7"
  - "3.5"
  - "3.6"
install:
  - python setup.py install
before_script:
  - flake8 .
script:
  - python setup.py test
after_success:
  - bash <(curl -s https://codecov.io/bash)
notifications:
  email:
    on_success: never
    on_failure: always
